keybinding:
  universal:
    goInto: L
    return: H
    prevItem: k
    nextItem: j
    prevItem-alt: <up>
    nextItem-alt: <down>
    scrollLeft: ''
    scrollRight: ''
    nextScreenMode: '+'
    prevScreenMode: '_'
gui:
  border: single
  showBottomLine: true
  portraitMode: always
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - '#969896'
    selectedLineBgColor:
      - '#4d4d4d'
git:
  pagers:
    - colorArg: always
      # pager: diff-so-fancy
      # delta has more granular diffing capabilities & support pin-pointing to the exact line of the change
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
